<?php
$MYSQL_HOST = 'YOUR_MYSQL_HOST';
$MYSQL_USER = 'YOUR_MYSQL_USERNAME';
$MYSQL_PASSWORD = 'YOUR_MYSQL_PASSWORD';
$MYSQL_DATABASE = 'YOUR_MYSQL_DATABASE_NAME';

$GOOGLE_CLIENT_ID = 'YOUR_GOOGLE_APP_CLIENT_ID';
?>
